### ISSUE TITLE
Style the FINAL DRAW section of index.html and link it to new webpage created to display team information

### ISSUE THREAD

**Issue by dhruv2185** [Nirvik07/FIFA_WORLD_CUP_2022#13]
- Full name :  Dhruv Ghevariya
- GitHub Profile Link : https://github.com/dhruv2185
- Participant ID (If not, then put NA) :NA
- Approach for this Project : Create new page to display information of a particular team (whose link is clicked by the user) and link them to the "FINAL DRAW" section of index.html. I would also like to improve the styling of FINAL DRAW section to make it more user-friendly.
-Participant role: Hacktoberfest 2022

**Comment by dhruv2185** [comment]
@Nirvik07 , Can I work on this?

**Comment by Nirvik07** [comment]
@dhruv2185 please fill up the google form. In the contributing.md file. If you have already done so, start with your work.

**Comment by dhruv2185** [comment]
Yes, I have filled the form and I am working on the issue....
