### ISSUE TITLE
CREATE A VENUE PAGE 

### ISSUE THREAD

**Issue by Nirvik07** [Nirvik07/FIFA_WORLD_CUP_2022#16]
**Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'Hacktoberfest' contributors of 'FIFA WORLD CUP 2022 Project'.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.)

# This page should contains all details of all the venues of FIFA WORLD CUP 2022.

**Comment by patelyash5208** [comment]
i have done that page @Asttttha @Nirvik07

**Comment by Nirvik07** [comment]
@patelyash5208 You need to first comment on an issue after that you will be assigned, then you can create PR. Then your PR will be merged. 
This is according to the rule of contribution in Hacktoberfest and any Open Source Program. 
And Assigning work as first comment first assigns . Please close your PR and wait for new issue or create your issue.

**Comment by patelyash5208** [comment]
I have created issue please assign to me.
