### ISSUE TITLE
EDIT THE SCHEDULE PDF IN THE RESOURCE FOLDER

### ISSUE THREAD

**Issue by Nirvik07** [Nirvik07/FIFA_WORLD_CUP_2022#17]
**Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'Hacktoberfest' contributors of 'FIFA WORLD CUP 2022 Project'.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.)

# This pdf must all the matches datails
Details are:
- Sl. No.
- Team 1 vs Team2 
- Time
- Venue
- Group No

Upload the File in Resource Folder.

**Comment by ilhamansari** [comment]
Full name : Md Ilham Ansari
GitHub Profile Link : https://github.com/ilhamansari
Participant ID (If not, then put NA) : NA
Approach for this Project : I will design the fixture schedule pdf in a very appealing and beautiful way.
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.)
Hactoberfest2022

**Comment by Priyanshu-su30** [comment]
Full name :Priyanshu Singh
GitHub Profile Link :https://github.com/Priyanshu-su30
Participant ID (If not, then put NA) :NA
Approach for this Project :I will make the pdf as u said attractive and amazing
What is your participant role? Hactoberfest2022

**Comment by Nirvik07** [comment]
@Priyanshu-su30 first comment first assign works here. Please wait for new issues.
