### ISSUE TITLE
CREATE A PAGE ON QATAR FOOTBALL AND LIFESTYLE

### ISSUE THREAD

**Issue by Nirvik07** [Nirvik07/FIFA_WORLD_CUP_2022#18]
**Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'Hacktoberfest' contributors of 'FIFA WORLD CUP 2022 Project'.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.)

# This project contains the details on football of Qatar and the lifestyle of Qatar. 
Qatar is the host country. Some details on Qatar's contribution to FIFA WORLD CUP 2022.

**Comment by Adityasaini10012001** [comment]
Can you assign this to me.

**Comment by alvinokafor** [comment]
Hi @Nirvik07, I would love to take up this issue. My details are as follows :

Full name : Alvin Chinedu Okafor
GitHub Profile Link : https://github.com/alvinokafor
Participant ID (If not, then put NA) : NA
Approach for this Project : I would use HTML, CSS and Javascript to create the page
Participant role: Hacktoberfest

**Comment by Nirvik07** [comment]
@Adityasaini10012001 you need to follow the issue template for getting an issue assign in your name.

**Comment by Nirvik07** [comment]
@alvinokafor please fill up the google form in contributing.md file. If you have done so, then start your work.
