### ISSUE TITLE
Add link on navbar and add Venus and how many match played at that stadium.. 

### ISSUE THREAD

**Issue by patelyash5208** [Nirvik07/FIFA_WORLD_CUP_2022#20]
**Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'Hacktoberfest' contributors of 'FIFA WORLD CUP 2022 Project'.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.)

**Comment by patelyash5208** [comment]
Please assign to me @Nirvik07

**Comment by patelyash5208** [comment]
Hi @Nirvik07, I would love to take up this issue. My details are as follows :

Full name : Patel Yashkumar Amitbhai 
GitHub Profile Link : https://github.com/patelyash5208
Participant ID (If not, then put NA) : NA
Approach for this Project : I would use HTML, CSS  to create the page
Participant role: Hacktoberfest

**Comment by Nirvik07** [comment]
@patelyash5208 please fill up the google form in contributing.md file. If you have done so, then start your work.

**Comment by patelyash5208** [comment]
I made a pull request please accept my request.
