### ISSUE TITLE
Change main page title and fix navigation

### ISSUE THREAD

**Issue by gfda** [Nirvik07/FIFA_WORLD_CUP_2022#38]
Hello I want to work on this issue.

Change this title
![image](https://user-images.githubusercontent.com/41340663/194680409-c90f677a-d980-4bc8-bde0-9e2292df8334.png)

Fix this navigation
![image](https://user-images.githubusercontent.com/41340663/194680665-f86820b7-5077-4b57-b7b0-821eba49abec.png)

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Gustavo Felipe Dias Alexandre
- GitHub Profile Link :  github.com/gfda
- Participant ID (If not, then put NA) : NA
- Approach for this Project :  I would use HTML, CSS and JS (if its necessary)
- What is your participant role? Hacktoberfest contributor

**Comment by Nirvik07** [comment]
@gfda please fill up the google form in the contributing.md file. If done so, start with your work. Please upload the file in the Projects Folder. Do not edit any file in the main directory. Create a copy for the files and then edit and then upload in the Projects folder.

**Comment by zaidsidd360** [comment]
Hey, @Nirvik07 , if @gfda isn't working on this issue anymore, could you assign it to me?

**Comment by zaidsidd360** [comment]
Oh, okay then, np bro. Wish you luck!
