### ISSUE TITLE
CREATE A WEBPAGE ON TEAM QATAR

### ISSUE THREAD

**Issue by Nirvik07** [Nirvik07/FIFA_WORLD_CUP_2022#43]
**Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'Hacktoberfest' contributors of 'FIFA WORLD CUP 2022 Project'.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.)

### Points to be noted:
The following details should be present in the webpage:
- Squad : A table containing the Name, Position, Age, Goals in past World Cups of all 23 player squad. Give the label of captain aside the player name. ( If the squad is not released , then fill with the latest lineup of the team.)
- Name of the Coach and his pic.
- The Team performance in the past World Cups.( include some iconic names)
- The Players to look out: (minimun 1 player or maximun 3 players)  The Stats of the player in football.
- Performance of the Team in Qualifying Round of FIFA WORLD CUP 2022.

**Comment by ilhamansari** [comment]
Full name : Md Ilham Ansari
GitHub Profile Link : https://github.com/ilhamansari
Participant ID (If not, then put NA) : NA
Approach for this Project : Will be making an appealing webpage of team Qatar including all the detials. 
What is your participant role? 
Hacktoberfest2022
