### ISSUE TITLE
Improvements to folder structure and file name standardization

### ISSUE THREAD

**Issue by gfda** [Nirvik07/FIFA_WORLD_CUP_2022#47]
I would like to suggest two tasks that can be divided into subtasks and people can work on them:

- Define a folder structure, ie:
    - Move css styles to "page-folder/css/styles.css";
    - Move media (imgs, svgs...) to "assets-folder/";

- Standardize folder and file names, we can talk about some naming standard that should be applied.

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Gustavo Felipe Dias Alexandre
- GitHub Profile Link :  github.com/gfda
- Participant ID (If not, then put NA) : gfda
- Approach for this Project :  Struct file and folders, define a naming convention.
- What is your participant role? Hacktoberfest contributor

**Comment by kraj2503** [comment]
To be Mentioned while taking the issue :

Full name : Kshitiz Raj
GitHub Profile Link : kraj2503
Participant ID (If not, then put NA) : NA
Approach for this Project : Will organise the whole project.
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.) HACKTOBERFEST

**Comment by gfda** [comment]
It's my suggestion for the naming convention. So, we can now break it down into subtasks.

1. Always use lower case when naming files and folders;

2. Don’t use spaces in file and folder names (use a dash instead);

3. Only use the characters [a-z], the numbers [0-9] and the dash/hyphen [-]

ex:
`about us/ -> about/ or about-us/`
`RESOURCES/ Team Page/ -> resources/team-page/`
...

@Nirvik07  Do you agree with this?

[reference](http://www.hoole.onl/04-02-starting.html)

**Comment by Nirvik07** [comment]
@gfda this issue cannot be accepted as a contribution. This work will be done by me and my team. So you are not allowed to make the changes. 
So please look for other issues. Please close this issue.

**Comment by gfda** [comment]
Ok, I'll close it.
Thanks.
