### ISSUE TITLE
CREATE AN ABOUTUS PAGE

### ISSUE THREAD

**Issue by Nirvik07** [Nirvik07/FIFA_WORLD_CUP_2022#6]
**Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'Hacktoberfest' contributors of 'FIFA WORLD CUP 2022 Project'.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC, Hactoberfest etc.)

# DESCRIPTIONS:
- The AboutUs should contact the details about FIFA WORLD CUP 2022.
- Design of the page should match with index page.
-  The project file must be uploaded in the Projects Folder.

**Comment by appledora** [comment]
Hi @Nirvik07 . I would love to give this issue a go. Could you assign this to me?

**Comment by scarnation** [comment]
Would love to take on this issue

**Comment by Nirvik07** [comment]
@scarnation you can't work on this. It is first come, first assign case according to the code of conduct of Hactoberfest and Open Source.

**Comment by Nirvik07** [comment]
@appledora please fill out the google form in the contributing.md. If you have already done, then start with your issue.

**Comment by appledora** [comment]
Thanks @Nirvik07 , I will fill up the form.

**Comment by scarnation** [comment]
alright

**Comment by scarnation** [comment]
can i get assigned another screen
